name: Build Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install dependencies and build
      run: |
        npm install --save-dev
        npm run build-docs

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: build
        folder: docs
